### ISSUE TITLE
C++20 coroutine support

### ISSUE THREAD

**Issue by niansa** [brainboxdotcc/DPP#175]
**Is your feature request related to a problem? Please describe.**
Some stuff is really hard to write on callbacks (see this for example: https://gitlab.com/niansa/tuxiflux/-/blob/master/bot/modules/warns.cpp#L17 - not written on DPP but I think it describes the problem preceisely)

**Describe the solution you'd like**
I'd love to have support for C++20 coroutines in DPP

**Comment by braindigitalis** [comment]
coroutines are very cool, I'm putting this on the back burner as a long term project until C++20 features are more widely supported by the default compilers packaged with popular stable distributions such as Debian.
any PR in the meantime would be accepted, but the library would still have to operate without support for C++20.

**Comment by niansa** [comment]
You can do it as boost asio does:

https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/overview/core/coroutines_ts.html

**Comment by braindigitalis** [comment]
yeah  any change like this though is a fundamental change to the library and a massive breaking change to existing code, which would have to be done very carefully.

**Comment by SirObby** [comment]
You could use a #if C++20
or something like that if it exists.

**Comment by braindigitalis** [comment]
the problem is, this way of returning values isn't just an internal tweak it's s fundamental difference in how the library works.

we'd have to support two different paradigms at the same time across two different C++ standard versions, this would be incredibly difficult and hard to maintain plus hard to support.

perhaps it's best to stick to one way of doing things, would we be changing this because its new and cool, or because that's how other languages discord libs are, or because it makes sense to make such a wide reaching breaking change?

not sure to me, right now it seems more trouble than its worth to completely rewrite an established library for a feature a lot of people can't even use yet (I don't even have GCC 11 on my development pc for instance and my production server runs GCC 8.3!)

**Comment by niansa** [comment]
Just wanted to say it's awesome you've been able to add it that quickly :-)
