### ISSUE TITLE
accent_color in user object

### ISSUE THREAD

**Issue by Commandserver** [brainboxdotcc/DPP#189]
**Is your feature request related to a problem? Please describe.**
`accent_color` is missing in the user object.

**Additional context**
https://discord.com/developers/docs/resources/user#user-object-user-structure

**Comment by braindigitalis** [comment]
we already have this, however it is in `dpp::user_identified`, a derived version of `dp::user` with more fields such as accent colour and banner hash, which is returned by user_get, current_user_get cluster calls etc.
This is because the value is not returned on the websocket at present and has to be explicitly asked for.
