### ISSUE TITLE
on_guild_update

### ISSUE THREAD

**Issue by 0gGhost** [brainboxdotcc/DPP#2]
From what i have tested, the on_guild_update is only triggered once per server after a server is edited, if you try to edit it after once, the event isnt triggered, as seen in the photo, once you restart the bot it can be triggered again

![image](https://user-images.githubusercontent.com/46922397/113293472-b7979080-92ed-11eb-8be4-e5c05975ae15.png)

Expected output there would be a new log in console with the server name being `POGGERS`

DM me brain if you dont know what i mean

**Comment by braindigitalis** [comment]
This seems related to another bug i was looking into.
Receiving a guild update removes it from the cache, this is why the second edit fails because it isn't there any more!

 2021-04-01 14:02:03.545 [I] [th#5615] : [G:31 U:11402 R:923 C:818] <TriviaBot#0000>  [Embed: ':question: Question 7 of 200']
 2021-04-01 14:02:05.184 [I] [th#5615] : [G:30 U:11402 R:923 C:818] Guild updated

How odd!

**Comment by 0gGhost** [comment]
I see, Is it removing the old guild data from cache but failing to gain the new guild data to put in cache?

**Comment by braindigitalis** [comment]
No, i had put `dpp::get_guild_cache()` where i meant to put `dpp::get_role_cache()`. It's fixed now :)
