### ISSUE TITLE
Dpp support for visual studio code

### ISSUE THREAD

**Issue by kuronight29** [brainboxdotcc/DPP#929]
I hope that in the future dpp will support visual studio code

**Comment by Jaskowicz1** [comment]
Hi there! DPP technically does work on Visual Studio Code, we just don't recommend it due to it not having all the features that Visual Studio or CLion does, along with it using MinGW. You can use CMake with Visual Studio Code though, which will let you work with DPP inside Visual Studio Code! You can also use WSL for DPP, with Visual Studio Code (and we have a tutorial for this too, which you can [visit here](https://dpp.dev/build-a-discord-bot-windows-wsl.html))!

**Comment by braindigitalis** [comment]
you can use visual studio code just fine; use wsl or ssh remote dev, or the msvc 2022 tool chain.
we do not recommend or directly support it with mingw.
